### ISSUE TITLE
Things for exos opinion

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoScummVM#290]
Did you verify my Beneath a Steel Sky volume changes are ok on a system different to mine?

---------------------------------------------------------------------------------------------

Should we make a note to user to press F5 to access scummvm volume options or save\load (depending on game) and F7 to load game (depending on game)? Its not obvious unless youve used scummvm before, but im not sure where we would put such a note. Certainly dont want it in the game launchers.

--------------------------------------------------------------------------------------------------

Not sure how to implement this into Day of the Tentacle. I currently have a user note in the front of the game launcher but didnt know about the "...but you have to add the game to ScummVM as well." bit. Heres the full quote I found:

*"At one point in the game, you come across a computer that allows you to play the original Maniac Mansion as an easter egg. ScummVM supports this, with a few caveats:

ScummVM will scan your configuration file for a game that's in a Maniac sub-folder of your Day of the Tentacle folder. If you've copied the data files from the CD version, this should already be the case but you have to add the game to ScummVM as well.

To return to Day of the Tentacle, press F5 and select "Return to Launcher"."*

Do you know where this computer in the game is for testing the feature?

-----------------------------------------------------------------------------------------------------

For Quest for Glory games im not sure how or if we can implement save transfers,  heres what I found so far:

*"It is possible to import characters, beginning with Quest for Glory II, from past games to future games and continue from the stats earned from those games.

For example, a character can be imported from Quest for Glory I directly to Quest for Glory III without having to necessarily play Quest for Glory II.

Characters cannot be imported from future games to past games, nor can a character be imported to the same game that was just completed. In other words, a character from Quest for Glory II cannot be imported into Quest for Glory II.

If you want to use a saved character from the original Sierra interpreter, you will need to rename the character file to "qfg[game-number]-[character-filename].sav" and place it in the ScummVM save path (see section 6.0), otherwise the file won't get listed on the import screen.

Example: qfg2-thief.sav"*

--------------------------------------------------------------------------------------------------

We need to remove the Mac version of Lighthouse unless the ScummVM dev fixes it before release as it currently crashes after the intro. Once removed we can keep a copy in the svn games folder for if\when it works. We will also need to swap lighthouse setup from a multi-platform to a single platform setup.

**Comment by exoscoriae** [comment]
1. Sounds good to me on this system.

2. This should be in the manual.

3. The computer is in the room on the right on the third floor. To get to it, you must first use bernard to discover the basement (open the grandfather clock) Then skip the cutscenes and you can head directly up stairs to the computer. Currently all three versions crash. I will start working on it and see what can be done. _(Update on progress below)_

4. I don't believe we should attempt to support save game transfer from the original interpreter. At that point we are dealing with people playing some of the games in dosbox and then deciding to try to go to scummvm... that is a mess. I am not opposed to attempting support for ScummVM to ScummVM gameplay though. The issue is, iirc, you can only import a completed save character. So, I can't just go make a guy in QFG1, save him, and then start testing the import process to QFG2. I believe I need a completed QFG1 save (from ScummVM) in order to do this. I'll have to spend some time on it. _(Update on progress below)_

5. How about keeping lighthouse as is, but just skipping the game select and having it go straight to the windows version? That way when Mac does work, we don't have to rebuild all the menus yet again?

**Comment by exoscoriae** [comment]
Maniac Mansion emulation:
So far I have found that even adding Maniac Mansion to the local scummvm installation does not fix this. Here are the variations:

- Local scummvm copy has DOTT & MM added. Launched from local copy - works
- Local scummvm copy has DOTT & MM added. Launched launcher (cmd line) - does not work, but gives verbose error
- Local scummvm copy has MM added. Launched launcher (cmd line) - does not work, drops to console error
- Project scummvm.ini file modified and loaded via command line with just MM - does not work, drops to console error
- Project scummvm.ini file modified and loaded via command line with DOTT & MM - does not work, drops to console error
- Both local and project scummvm.ini files have both games loaded to them - does not work, drops to console error

**verbose error** - what I mean by this, is ScummVM actually pops up a dialogue saying Maniac Mansion would launch at this point _if_ you had it in the MANIAC folder underneath your DOTT installation **and** you had the game added to ScummVM. Ironically, the only way I get this message is if the game **is** added to the local scummvm.ini file. Adding it to the one we keep in the scmvm folder (and adding a call to it from the command line) does not work.

Essentially, at this point I have not found a successful way to get this to work via *any* command line launches I have tried. The closest I've come is having both games present in the user's scummvm.ini file (appdata\roaming\scummvm\). With that, I at least get the verbose error message instead of a crash.

**Comment by exoscoriae** [comment]
QFG Imports:
I was able to test and verify the process of bringing in a completed character from the DOS version. So, this at least shows that having a properly named file in your appdata\roaming\scummvm\saved games\ folder does technically work. That said, I still don't think we should try to automate this process at all. 

So the next question is, if you finish a game IN scummvm and the choose to create the final save file that can be imported into the next game, then does scummvm save this properly without any effort needed on our part?

I can't find any sure fire proof of this so far. Just anecdotes and lots of threads saying it "should" work.

Short of actually playing through the game though, I don't know of any way to test this. I spent some time searching for scummvm native save files near the end of the game, but so far I've come up empty handed.

**Comment by exoscoriae** [comment]
QFG:
https://bugs.scummvm.org/ticket/5305

This suggests the issue has been addressed and does work. I believe we can safely just note that games *can* be imported from game to game, but not have to do anything on our end to support it.

**Comment by Python-Exoproject** [comment]
1. Sweet, ill assume that means the same for others ive done this to.
2. No Problem
3. Now that I know where it is in the game Ive tried as well and no joy with our method of game launch. I guess we will have to park this unless something changes in the future. We will need to change the user note Ive added to the launch bat, you ok to do that or you like me to?
4. Agreed, its probably working
5. We can do as you suggest, but it will be the only "Multi-Platform" game with only one running version. If thats no issue to you then Im happy to make the change

**Comment by exoscoriae** [comment]
3. I'll change the user note this morning
5. Doesn't bother me. Technically the data for both platforms will still be there. It's really just a matter of changing the launch file to skip the questions and go straight to the DOS version. I'll do that as well this morning since I am already going to be syncing the other change.
